server:
  port: 8087
spring:
  datasource:
#      url: 'jdbc:h2:./database/samspledb;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=TRUE'
    url: jdbc:postgresql://localhost:5432/lr3881
    driverClassName: org.postgresql.Driver
    username: product
    password: product
    hibernate:
      ddl-auto: create-drop
